### ISSUE TITLE
[JOSS]: Report issues/Seeking support

### ISSUE THREAD

**Issue by adswa** [MLHale/gazepoint-websockets#4]
With respect to 
>  Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I found guidelines on how to contribute in `CONTRIBUTING.md`, but I did not find information on how to report issues/problems. Could you add this to your `CONTRIBUTING.md` file, or elsewhere in your repository?

Belongs to  [this JOSS review](https://github.com/openjournals/joss-reviews/issues/1620).

**Comment by MLHale** [comment]
I will add it this evening, as soon as I am back to my desk. Thanks.

**Comment by MLHale** [comment]
@adswa 

I added the requested report/support details patterned after other open source projects. The `contributing.md` file has been updated in 3dab6c7

Thanks.

**Comment by adswa** [comment]
Awesome :rocket:
