### ISSUE TITLE
[JOSS]: (Automated) testing

### ISSUE THREAD

**Issue by adswa** [MLHale/gazepoint-websockets#6]
Hey @MLHale, 

as I don't have access to the hardware, I'm trying to figure out how much of the software I can review. Referring to 

>  Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?

I wanted to ask whether there is any testing suite. I can't find tests in `api/tests.py`, or in other places in the repo. Am I missing something? Thanks!

Belongs to [this review](https://github.com/openjournals/joss-reviews/issues/1620).

**Comment by MLHale** [comment]
hi @adswa 

There are no automated tests in eyestream, but there are manual steps for verifying the functionality of the software.

The manual steps are in the README under the "starting a clientside websocket" heading.

Really there are only 3 user-level tests:

- server starts when called upon to do so via a websocket open message. Expected starting behavior includes launching the gazepoint hardware controller, turning on the gazepoint device, and beginning to stream captured eye data to the websocket which instantiated the channel.
- server streams data captured by the hardware to the websocket client as long as the websocket is open
- server ends a session when called upon to do so via a websocket close event or if the websocket times out. Expected termination behavior is to disable further data collection, gracefully shut down the eye tracker hardware and controller, join the threads supporting the data capture process, and end server processing related to the websocket.

The main processing of these behaviors occurs in the socketconsumers.py file: https://github.com/MLHale/eyestream/blob/master/api/socketconsumers.py

The driver modifications to the PyOpenGaze library that act as middleware between the hardware and server layers are in:

https://github.com/MLHale/eyestream/blob/master/GazepointAnalysis/GazepointWebsockets.py

If needed, I can add these more concrete test criteria to the readme and include some expected outcomes.

**Comment by MLHale** [comment]
Most of the other files in the repo are basic Django server files that are similar to those of any other django 1.11 installation for an arbitrary web server.

**Comment by MLHale** [comment]
Hi @adswa - I went ahead and made some changes to the readme file. I recognize that it is not as verbose or complete as an automated test suite, but it does at least provide some manual testing steps and expected outcomes.

**Comment by MLHale** [comment]
Hi @adswa - Is any other action needed on this issue?

**Comment by adswa** [comment]
So sorry, @MLHale , I was sure I'd replied and closed this after your readme update already! Thanks for the poke, and sorry for the delay!

**Comment by MLHale** [comment]
@adswa - No worries! Thanks.
